<a href="https://colab.research.google.com/github/jassynavarro/CCMACLRL_EXERCISES_COM221/blob/main/Exercise9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercise 9: Choosing the best performing model on a dataset

Instructions:

- Use the Dataset File to train your model
- Use the Test File to generate your results
- Use the Sample Submission file to generate the same format
- Use all classification models

Submit your results to:
https://www.kaggle.com/competitions/playground-series-s4e10/overview

In [543]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from matplotlib import pyplot as plt

import warnings as wrn
wrn.filterwarnings('ignore')

## Dataset File

In [544]:
dataset_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/train.csv?raw=true'
df = pd.read_csv(dataset_url)

In [545]:
df.head(30)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0
5,5,27,45000,RENT,2.0,VENTURE,A,9000,8.94,0.20,N,5,0
6,6,25,45000,MORTGAGE,9.0,EDUCATION,A,12000,6.54,0.27,N,3,0
7,7,21,20000,RENT,0.0,PERSONAL,C,2500,13.49,0.13,Y,3,0
8,8,37,69600,RENT,11.0,EDUCATION,D,5000,14.84,0.07,Y,11,0
9,9,35,110000,MORTGAGE,0.0,DEBTCONSOLIDATION,C,15000,12.98,0.14,Y,6,0
10,10,30,78000,MORTGAGE,5.0,VENTURE,B,12800,10.59,0.17,N,5,0
11,11,22,33000,RENT,6.0,PERSONAL,B,10000,11.12,0.30,N,2,1
12,12,25,33000,MORTGAGE,1.0,EDUCATION,B,4000,10.75,0.12,N,3,0
13,13,31,70000,MORTGAGE,2.0,DEBTCONSOLIDATION,B,16000,11.14,0.23,N,9,0
14,14,27,100000,RENT,1.0,HOMEIMPROVEMENT,C,5000,13.57,0.05,Y,7,0
15,15,29,33000,OWN,8.0,MEDICAL,A,7300,8.90,0.23,N,8,0
16,16,26,80000,RENT,2.0,HOMEIMPROVEMENT,D,17000,14.11,0.21,Y,3,0
17,17,29,60000,OWN,13.0,MEDICAL,A,15000,6.62,0.25,N,9,0
18,18,22,84000,MORTGAGE,6.0,DEBTCONSOLIDATION,B,5950,11.12,0.07,N,4,0
19,19,27,65000,MORTGAGE,3.0,DEBTCONSOLIDATION,C,4800,12.73,0.07,Y,8,0
20,20,28,45000,OWN,0.0,PERSONAL,A,3200,7.88,0.07,N,5,0
21,21,22,45000,MORTGAGE,3.0,PERSONAL,A,7000,8.59,0.16,N,4,0
22,22,26,95000,MORTGAGE,10.0,EDUCATION,A,10000,7.68,0.11,N,3,0
23,23,27,33000,RENT,2.0,VENTURE,A,3000,6.99,0.09,N,6,0
24,24,22,30000,RENT,3.0,MEDICAL,D,5000,16.49,0.17,N,4,1
25,25,25,25000,RENT,3.0,VENTURE,C,3500,13.49,0.14,Y,3,1
26,26,28,75000,MORTGAGE,12.0,VENTURE,A,14000,7.88,0.19,N,5,0
27,27,21,45000,RENT,5.0,DEBTCONSOLIDATION,A,2800,6.54,0.06,N,4,0
28,28,32,122004,MORTGAGE,13.0,MEDICAL,A,10000,8.59,0.08,N,9,0
29,29,23,50000,RENT,4.0,PERSONAL,B,6000,11.49,0.12,N,2,0

In [546]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          58645 non-null  int64
 1   person_age                  58645 non-null  int64
 2   person_income               58645 non-null  int64
 3   person_home_ownership       58645 non-null  object
 4   person_emp_length           58645 non-null  float64
 5   loan_intent                 58645 non-null  object
 6   loan_grade                  58645 non-null  object
 7   loan_amnt                   58645 non-null  int64
 8   loan_int_rate               58645 non-null  float64
 9   loan_percent_income         58645 non-null  float64
 10  cb_person_default_on_file   58645 non-null  object
 11  cb_person_cred_hist_length  58645 non-null  int64
 12  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(6), object(4)
memory usage: 5.8+ MB

In [547]:
df['person_home_ownership'] = df['person_home_ownership'].map({'RENT': 0, 'MORTGAGE': 1,'OWN' : 2, 'OTHER': 3})
df.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0
5,5,27,45000,0,2.0,VENTURE,A,9000,8.94,0.20,N,5,0
6,6,25,45000,1,9.0,EDUCATION,A,12000,6.54,0.27,N,3,0
7,7,21,20000,0,0.0,PERSONAL,C,2500,13.49,0.13,Y,3,0
8,8,37,69600,0,11.0,EDUCATION,D,5000,14.84,0.07,Y,11,0
9,9,35,110000,1,0.0,DEBTCONSOLIDATION,C,15000,12.98,0.14,Y,6,0

In [548]:
df['loan_intent'] = df['loan_intent'].map({'EDUCATION': 0, 'MEDICAL': 1,'PERSONAL' : 2, 'VENTURE': 3, 'DEBTCONSOLIDATION': 4, 'HOMEIMPROVEMENT': 5})
df.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,B,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,1,C,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,2,A,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,3,B,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,1,A,6000,6.92,0.10,N,3,0
5,5,27,45000,0,2.0,3,A,9000,8.94,0.20,N,5,0
6,6,25,45000,1,9.0,0,A,12000,6.54,0.27,N,3,0
7,7,21,20000,0,0.0,2,C,2500,13.49,0.13,Y,3,0
8,8,37,69600,0,11.0,0,D,5000,14.84,0.07,Y,11,0
9,9,35,110000,1,0.0,4,C,15000,12.98,0.14,Y,6,0

In [549]:
df['loan_grade'] = df['loan_grade'].map({'A': 0, 'B': 1,'C' : 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6})
df.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,1,6000,11.49,0.17,N,14,0
1,1,22,56000,2,6.0,1,2,4000,13.35,0.07,N,2,0
2,2,29,28800,2,8.0,2,0,6000,8.90,0.21,N,10,0
3,3,30,70000,0,14.0,3,1,12000,11.11,0.17,N,5,0
4,4,22,60000,0,2.0,1,0,6000,6.92,0.10,N,3,0
5,5,27,45000,0,2.0,3,0,9000,8.94,0.20,N,5,0
6,6,25,45000,1,9.0,0,0,12000,6.54,0.27,N,3,0
7,7,21,20000,0,0.0,2,2,2500,13.49,0.13,Y,3,0
8,8,37,69600,0,11.0,0,3,5000,14.84,0.07,Y,11,0
9,9,35,110000,1,0.0,4,2,15000,12.98,0.14,Y,6,0

In [550]:
df['cb_person_default_on_file'] = df['cb_person_default_on_file'].map({'N': 0, 'Y': 1})
df.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,0,0.0,0,1,6000,11.49,0.17,0,14,0
1,1,22,56000,2,6.0,1,2,4000,13.35,0.07,0,2,0
2,2,29,28800,2,8.0,2,0,6000,8.90,0.21,0,10,0
3,3,30,70000,0,14.0,3,1,12000,11.11,0.17,0,5,0
4,4,22,60000,0,2.0,1,0,6000,6.92,0.10,0,3,0
5,5,27,45000,0,2.0,3,0,9000,8.94,0.20,0,5,0
6,6,25,45000,1,9.0,0,0,12000,6.54,0.27,0,3,0
7,7,21,20000,0,0.0,2,2,2500,13.49,0.13,1,3,0
8,8,37,69600,0,11.0,0,3,5000,14.84,0.07,1,11,0
9,9,35,110000,1,0.0,4,2,15000,12.98,0.14,1,6,0

In [551]:
df.drop(['id'],axis=1,inplace=True)

In [552]:
from sklearn.model_selection import train_test_split
x = df.drop("loan_status",axis=1)
y = df["loan_status"]

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=0.3)

In [553]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,37,35000,0,0.0,0,1,6000,11.49,0.17,0,14,0
1,22,56000,2,6.0,1,2,4000,13.35,0.07,0,2,0
2,29,28800,2,8.0,2,0,6000,8.90,0.21,0,10,0
3,30,70000,0,14.0,3,1,12000,11.11,0.17,0,5,0
4,22,60000,0,2.0,1,0,6000,6.92,0.10,0,3,0

In [554]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  58645 non-null  int64
 1   person_income               58645 non-null  int64
 2   person_home_ownership       58645 non-null  int64
 3   person_emp_length           58645 non-null  float64
 4   loan_intent                 58645 non-null  int64
 5   loan_grade                  58645 non-null  int64
 6   loan_amnt                   58645 non-null  int64
 7   loan_int_rate               58645 non-null  float64
 8   loan_percent_income         58645 non-null  float64
 9   cb_person_default_on_file   58645 non-null  int64
 10  cb_person_cred_hist_length  58645 non-null  int64
 11  loan_status                 58645 non-null  int64
dtypes: float64(3), int64(9)
memory usage: 5.4 MB

## Test File

In [555]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/test.csv?raw=true'
dt=pd.read_csv(test_url)

In [556]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          39098 non-null  int64
 1   person_age                  39098 non-null  int64
 2   person_income               39098 non-null  int64
 3   person_home_ownership       39098 non-null  object
 4   person_emp_length           39098 non-null  float64
 5   loan_intent                 39098 non-null  object
 6   loan_grade                  39098 non-null  object
 7   loan_amnt                   39098 non-null  int64
 8   loan_int_rate               39098 non-null  float64
 9   loan_percent_income         39098 non-null  float64
 10  cb_person_default_on_file   39098 non-null  object
 11  cb_person_cred_hist_length  39098 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.6+ MB

In [557]:
dt['person_home_ownership'] = dt['person_home_ownership'].map({'RENT': 0, 'MORTGAGE': 1,'OWN' : 2, 'OTHER': 3})
dt.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,HOMEIMPROVEMENT,F,25000,15.76,0.36,N,2
1,58646,26,96000,1,6.0,PERSONAL,C,10000,12.68,0.10,Y,4
2,58647,26,30000,0,5.0,VENTURE,E,4000,17.19,0.13,Y,2
3,58648,33,50000,0,4.0,DEBTCONSOLIDATION,A,7000,8.90,0.14,N,7
4,58649,26,102000,1,8.0,HOMEIMPROVEMENT,D,15000,16.32,0.15,Y,4
5,58650,23,66000,0,5.0,EDUCATION,D,22000,14.09,0.33,N,2
6,58651,26,75000,2,10.0,PERSONAL,B,8000,10.62,0.11,N,4
7,58652,23,55000,1,6.0,PERSONAL,A,6250,6.76,0.12,N,2
8,58653,32,29124,0,0.0,PERSONAL,C,7200,13.11,0.26,Y,6
9,58654,22,90000,0,4.0,DEBTCONSOLIDATION,C,10000,13.49,0.11,Y,3

In [558]:
dt['loan_intent'] = dt['loan_intent'].map({'EDUCATION': 0, 'MEDICAL': 1,'PERSONAL' : 2, 'VENTURE': 3, 'DEBTCONSOLIDATION': 4, 'HOMEIMPROVEMENT': 5})
dt.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,5,F,25000,15.76,0.36,N,2
1,58646,26,96000,1,6.0,2,C,10000,12.68,0.10,Y,4
2,58647,26,30000,0,5.0,3,E,4000,17.19,0.13,Y,2
3,58648,33,50000,0,4.0,4,A,7000,8.90,0.14,N,7
4,58649,26,102000,1,8.0,5,D,15000,16.32,0.15,Y,4
5,58650,23,66000,0,5.0,0,D,22000,14.09,0.33,N,2
6,58651,26,75000,2,10.0,2,B,8000,10.62,0.11,N,4
7,58652,23,55000,1,6.0,2,A,6250,6.76,0.12,N,2
8,58653,32,29124,0,0.0,2,C,7200,13.11,0.26,Y,6
9,58654,22,90000,0,4.0,4,C,10000,13.49,0.11,Y,3

In [559]:
dt['loan_grade'] = dt['loan_grade'].map({'A': 0, 'B': 1,'C' : 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6})
dt.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,5,5,25000,15.76,0.36,N,2
1,58646,26,96000,1,6.0,2,2,10000,12.68,0.10,Y,4
2,58647,26,30000,0,5.0,3,4,4000,17.19,0.13,Y,2
3,58648,33,50000,0,4.0,4,0,7000,8.90,0.14,N,7
4,58649,26,102000,1,8.0,5,3,15000,16.32,0.15,Y,4
5,58650,23,66000,0,5.0,0,3,22000,14.09,0.33,N,2
6,58651,26,75000,2,10.0,2,1,8000,10.62,0.11,N,4
7,58652,23,55000,1,6.0,2,0,6250,6.76,0.12,N,2
8,58653,32,29124,0,0.0,2,2,7200,13.11,0.26,Y,6
9,58654,22,90000,0,4.0,4,2,10000,13.49,0.11,Y,3

In [560]:
dt['cb_person_default_on_file'] = dt['cb_person_default_on_file'].map({'N': 0, 'Y': 1})
dt.head(10)

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,58645,23,69000,0,3.0,5,5,25000,15.76,0.36,0,2
1,58646,26,96000,1,6.0,2,2,10000,12.68,0.10,1,4
2,58647,26,30000,0,5.0,3,4,4000,17.19,0.13,1,2
3,58648,33,50000,0,4.0,4,0,7000,8.90,0.14,0,7
4,58649,26,102000,1,8.0,5,3,15000,16.32,0.15,1,4
5,58650,23,66000,0,5.0,0,3,22000,14.09,0.33,0,2
6,58651,26,75000,2,10.0,2,1,8000,10.62,0.11,0,4
7,58652,23,55000,1,6.0,2,0,6250,6.76,0.12,0,2
8,58653,32,29124,0,0.0,2,2,7200,13.11,0.26,1,6
9,58654,22,90000,0,4.0,4,2,10000,13.49,0.11,1,3

In [561]:
dt.drop(['id'],axis=1,inplace=True)

In [562]:
dt.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,23,69000,0,3.0,5,5,25000,15.76,0.36,0,2
1,26,96000,1,6.0,2,2,10000,12.68,0.10,1,4
2,26,30000,0,5.0,3,4,4000,17.19,0.13,1,2
3,33,50000,0,4.0,4,0,7000,8.90,0.14,0,7
4,26,102000,1,8.0,5,3,15000,16.32,0.15,1,4

## Sample Submission File

In [563]:
sample_submission_url ='https://github.com/robitussin/CCMACLRL_EXERCISES/blob/main/datasets/loan_approval/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

In [564]:
sf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39098 entries, 0 to 39097
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39098 non-null  int64
 1   loan_status  39098 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 611.0 KB

## 1. Train a KNN Classifier

In [565]:
# put your answer here

In [566]:
score_list = {} # I've created this dict for saving score variables into it

In [567]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=22) #I've tried more than 50 values. 22 is the best value

KNN.fit(x_train,y_train)
knn_score = KNN.score(x_test,y_test)
print(f"Score is {knn_score}")

Score is 0.8932590655905422

- Perform cross validation

In [568]:
# put your answer here

In [569]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(KNN, x, y, cv=5)
scores

array([0.89368233, 0.89257396, 0.89402336, 0.89282974, 0.89240344])

In [570]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.89 accuracy with a standard deviation of 0.00

In [571]:
score_list["KNN Classifier"] = scores.mean()

## 2. Train a Logistic Regression Classifier

In [572]:
# put your answer here

In [573]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(x_train,y_train)

lr_score = LR.score(x_test,y_test)

print(f"Score is {lr_score}")

Score is 0.8845629191769921

- Perform cross validation

In [574]:
# put your answer here

In [575]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(LR, x, y, cv=5)
scores

array([0.88387757, 0.88532697, 0.88362179, 0.88345127, 0.88626481])

In [576]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.88 accuracy with a standard deviation of 0.00

In [577]:
score_list["Logistic Regression"] = scores.mean()

## 3. Train a Naive Bayes Classifier

In [578]:
# put your answer here

In [579]:
from sklearn.naive_bayes import GaussianNB

nbc = GaussianNB()
nbc.fit(x_train,y_train)
nbc_score = nbc.score(x_test,y_test)

print(f"Score is {nbc_score}")

Score is 0.8848471069682846

- Perform cross validation

In [580]:
# put your answer here

In [581]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(nbc, x, y, cv=5)
scores

array([0.88140506, 0.88541223, 0.88583852, 0.8871174 , 0.88490067])

In [582]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.88 accuracy with a standard deviation of 0.00

In [583]:
score_list["GaussianNBC"] = scores.mean()

## 4. Train a SVM Classifier

In [584]:
# put your answer here

In [585]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train,y_train)
svc_score = svc.score(x_test,y_test)
print(f"Score is {svc_score}")

Score is 0.8579061043537569

- Perform cross validation

In [586]:
# put your answer here

In [587]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(svc, x, y, cv=5)
scores

array([0.85761787, 0.85761787, 0.85761787, 0.85753261, 0.85761787])

In [588]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.86 accuracy with a standard deviation of 0.00

In [589]:
score_list["SVC"] = scores.mean()

## 5. Train a Decision Tree Classifier

In [590]:
# put your answer here

In [591]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1)
dtc.fit(x_train,y_train)

dtc_score = dtc.score(x_test,y_test)
print(f"Score is {dtc_score}")

Score is 0.9119017846993294

- Perform cross validation

In [592]:
# put your answer here

In [593]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dtc, x, y, cv=5)
scores

array([0.91226874, 0.90996675, 0.91422969, 0.91559383, 0.91278029])

In [594]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.91 accuracy with a standard deviation of 0.00

In [595]:
score_list["DTC"] = scores.mean()

## 6. Train a Random Forest Classifier

In [596]:
# put your answer here

In [597]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=50,random_state=1)
rfc.fit(x_train,y_train)
rfc_score = rfc.score(x_test,y_test)
score_list["RFC"]=rfc_score

print(f"Score is {rfc_score}")

Score is 0.9509491872229169

## 7. Compare all the performance of all classification models

In [598]:
# put your answer here

In [599]:
score_list = list(score_list.items())
for alg,score in score_list:
    print(f"{alg} Score is {str(score)[:4]} ")

KNN Classifier Score is 0.89
Logistic Regression Score is 0.88
GaussianNBC Score is 0.88
SVC Score is 0.85
DTC Score is 0.91
RFC Score is 0.95

## 9. Generate Submission File

Choose the model that has the best performance to generate a submission file.

In [600]:
model = RandomForestClassifier(n_estimators=50,random_state=1)

In [601]:
sf.head()

      id  loan_status
0  58645          0.5
1  58646          0.5
2  58647          0.5
3  58648          0.5
4  58649          0.5

In [602]:
dt.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,23,69000,0,3.0,5,5,25000,15.76,0.36,0,2
1,26,96000,1,6.0,2,2,10000,12.68,0.10,1,4
2,26,30000,0,5.0,3,4,4000,17.19,0.13,1,2
3,33,50000,0,4.0,4,0,7000,8.90,0.14,0,7
4,26,102000,1,8.0,5,3,15000,16.32,0.15,1,4

In [603]:
id = sf.pop('id')
y_pred = rfc.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'loan_status': y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv